<#
.SYNOPSIS
  Install telegram-bot-mcp as a Windows Scheduled Task that starts at logon and
  restarts on failure (T5.4). Runs in YOUR user session so it uses your existing
  `claude` login. No admin rights required.

.NOTES
  Run this yourself from an interactive PowerShell — it is NOT invoked by the
  agent (the guardrail deny-list blocks schtasks from agent sessions by design).

.EXAMPLE
  pwsh -File scripts/install-windows.ps1
#>
[CmdletBinding()]
param(
  [string]$TaskName = "TelegramBotMCP"
)

$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent $PSScriptRoot
Write-Host "Project: $projectRoot"

# 1. Ensure dependencies + a fresh build.
Push-Location $projectRoot
try {
  if (-not (Test-Path (Join-Path $projectRoot "node_modules"))) {
    Write-Host "Installing dependencies..."
    npm ci
  }
  Write-Host "Building..."
  npm run build

  $entry = Join-Path $projectRoot "dist\main.js"
  if (-not (Test-Path $entry)) { throw "Build did not produce dist\main.js" }
  if (-not (Test-Path (Join-Path $projectRoot ".env"))) {
    Write-Warning "No .env found. Copy .env.example to .env and set BOT_TOKEN before the bot will run."
  }

  $node = (Get-Command node).Source

  # 2. Define the scheduled task: at logon, restart every 1 min up to 999 times.
  $action = New-ScheduledTaskAction -Execute $node -Argument "`"$entry`"" -WorkingDirectory $projectRoot
  $trigger = New-ScheduledTaskTrigger -AtLogOn
  $settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -RestartInterval (New-TimeSpan -Minutes 1) -RestartCount 999 `
    -ExecutionTimeLimit (New-TimeSpan -Hours 0) -StartWhenAvailable
  $principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited

  if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Write-Host "Updating existing task '$TaskName'..."
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
  }

  # Registering a task needs elevation on some machines. Fall back to the user's
  # Startup folder, which needs no admin rights and gives the same outcome
  # (launch at logon, restart on failure via the supervisor loop in tbm-run.cmd).
  $registered = $false
  try {
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
      -Settings $settings -Principal $principal `
      -Description "Telegram <-> Claude Code bridge daemon" -ErrorAction Stop | Out-Null
    $registered = $true
  } catch {
    Write-Warning "Scheduled Task registration failed ($($_.Exception.Message.Trim()))."
    Write-Host "Falling back to the Startup folder (no admin rights needed)."
  }

  if ($registered) {
    Write-Host "`nInstalled scheduled task '$TaskName'." -ForegroundColor Green
    Write-Host "Start it now with:  Start-ScheduledTask -TaskName $TaskName"
  }
  else {
    $startup = [Environment]::GetFolderPath('Startup')
    $link = Join-Path $startup "TelegramBotMCP.vbs"
    $launcher = Join-Path $projectRoot "scripts\tbm-launch.vbs"
    if (-not (Test-Path $launcher)) { throw "Missing $launcher" }
    # A tiny shim in Startup that calls the real launcher, so moving/updating the
    # project never leaves a stale copy behind.
    @"
' Auto-generated by install-windows.ps1 - starts the telegram-bot-mcp daemon at logon.
CreateObject("WScript.Shell").Run """$launcher""", 0, False
"@ | Set-Content -Path $link -Encoding ASCII
    Write-Host "`nInstalled Startup launcher: $link" -ForegroundColor Green
    Write-Host "Start it now with:  wscript `"$launcher`""
    Write-Host "(For the Scheduled Task version instead, re-run this script from an elevated PowerShell.)"
  }

  Write-Host "Watch logs with:    Get-Content `"$projectRoot\data\daemon.log`" -Wait"
  Write-Host "Uninstall with:     pwsh -File scripts\uninstall-windows.ps1"
}
finally {
  Pop-Location
}
